import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import {
  BookOpen, Sparkles, Loader2, Globe, Plus, FileCode, Layers,
  ListChecks, Lock, AlertTriangle, ChevronRight, Wand2, Trash2, ListPlus, Download,
  Database, Workflow, Plug,
} from "lucide-react";
import jsPDF from "jspdf";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

import SuggestedWebsites from "@/components/SuggestedWebsites";
import SmartUrlError from "@/components/SmartUrlError";
import { isProbablyValidUrl, normalizeUrl } from "@/lib/urlSuggest";
import FixIntentDialog, { FixIntent } from "@/components/FixIntentDialog";

interface WebsiteRow { id: string; url: string; name: string | null; }

interface DocsResult {
  project_overview: string;
  tech_stack_guess: { name: string; why_we_think_so: string }[];
  architecture: string;
  architecture_diagram?: { name: string; role: string; layer: string; connects_to: string[] }[];
  database_schema_guess?: { name: string; purpose: string; key_fields: string[] }[];
  user_workflows?: { name: string; steps: string[] }[];
  integrations?: { name: string; purpose: string }[];
  key_pages: { path: string; purpose: string }[];
  local_setup: string[];
  env_vars_likely: string[];
  gotchas: string[];
  first_week_checklist: string[];
}

interface FeaturesResult {
  detected: { name: string; description: string; category: string; confidence: string }[];
  recommended: { name: string; why: string; impact: string }[];
  summary: string;
}

const TechDocs = () => {
  const { user } = useAuth();
  const [websites, setWebsites] = useState<WebsiteRow[]>([]);
  const [activeUrl, setActiveUrl] = useState("");
  const [newUrl, setNewUrl] = useState("");
  const [adding, setAdding] = useState(false);
  const [tab, setTab] = useState<"docs" | "features">("docs");
  const [docs, setDocs] = useState<DocsResult | null>(null);
  const [features, setFeatures] = useState<FeaturesResult | null>(null);
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState(0);
  const [urlError, setUrlError] = useState<string | null>(null);
  const [intentOpen, setIntentOpen] = useState(false);
  const [pendingMode, setPendingMode] = useState<"docs" | "features" | null>(null);
  const [exporting, setExporting] = useState(false);

  const exportDocsPdf = async () => {
    if (!docs) return;
    setExporting(true);
    try {
      const pdf = new jsPDF("p", "mm", "a4");
      const pageW = 210;
      const pageH = 297;
      const margin = 18;
      const maxW = pageW - margin * 2;
      let y = margin;

      const ensureSpace = (need: number) => {
        if (y + need > pageH - margin) {
          pdf.addPage();
          y = margin;
        }
      };

      const writeWrapped = (text: string, size: number, style: "normal" | "bold" = "normal", color: [number, number, number] = [30, 30, 30]) => {
        pdf.setFont("helvetica", style);
        pdf.setFontSize(size);
        pdf.setTextColor(color[0], color[1], color[2]);
        const lines = pdf.splitTextToSize(text || "", maxW);
        for (const line of lines) {
          ensureSpace(size * 0.5);
          pdf.text(line, margin, y);
          y += size * 0.5;
        }
      };

      const heading = (text: string) => {
        ensureSpace(14);
        y += 4;
        writeWrapped(text, 14, "bold", [20, 20, 20]);
        pdf.setDrawColor(220, 220, 220);
        pdf.line(margin, y, pageW - margin, y);
        y += 4;
      };

      const subheading = (text: string) => {
        ensureSpace(10);
        writeWrapped(text, 11, "bold", [50, 50, 50]);
        y += 1;
      };

      const bullet = (text: string) => writeWrapped(`•  ${text}`, 10, "normal", [40, 40, 40]);

      // Cover
      pdf.setFillColor(15, 23, 42);
      pdf.rect(0, 0, pageW, 60, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(22);
      pdf.text("Onboarding Document", margin, 30);
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.text(activeUrl || "", margin, 42);
      pdf.setFontSize(9);
      pdf.setTextColor(180, 180, 180);
      pdf.text(`Generated by Project Bond · ${new Date().toLocaleDateString()}`, margin, 52);
      y = 78;

      heading("Project Overview");
      writeWrapped(docs.project_overview, 10);

      heading("Likely Tech Stack");
      docs.tech_stack_guess.forEach(t => {
        subheading(t.name);
        writeWrapped(t.why_we_think_so, 10);
      });

      heading("Architecture");
      writeWrapped(docs.architecture, 10);

      if (docs.architecture_diagram?.length) {
        subheading("Components");
        docs.architecture_diagram.forEach(c => {
          bullet(`${c.name} (${c.layer}) — ${c.role}`);
          if (c.connects_to?.length) writeWrapped(`   ↳ connects to: ${c.connects_to.join(", ")}`, 9, "normal", [110, 110, 110]);
        });
      }

      if (docs.database_schema_guess?.length) {
        heading("Likely Database Schema");
        docs.database_schema_guess.forEach(t => {
          subheading(t.name);
          writeWrapped(t.purpose, 10);
          writeWrapped(`Fields: ${t.key_fields.join(", ")}`, 9, "normal", [100, 100, 100]);
        });
      }

      if (docs.user_workflows?.length) {
        heading("User Workflows");
        docs.user_workflows.forEach(w => {
          subheading(w.name);
          w.steps.forEach((s, i) => bullet(`${i + 1}. ${s}`));
        });
      }

      if (docs.integrations?.length) {
        heading("Integrations");
        docs.integrations.forEach(i => bullet(`${i.name} — ${i.purpose}`));
      }

      heading("Key Pages");
      docs.key_pages.forEach(p => bullet(`${p.path} — ${p.purpose}`));

      heading("Local Setup");
      docs.local_setup.forEach((s, i) => bullet(`${i + 1}. ${s}`));

      heading("Likely Env Vars");
      writeWrapped(docs.env_vars_likely.join(", "), 10);

      heading("Gotchas");
      docs.gotchas.forEach(g => bullet(g));

      heading("First Week Checklist");
      docs.first_week_checklist.forEach(c => bullet(`☐  ${c}`));

      // Page numbers
      const total = pdf.getNumberOfPages();
      for (let i = 1; i <= total; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        pdf.text(`${i} / ${total}`, pageW - margin, pageH - 8, { align: "right" });
      }

      const safeName = (activeUrl || "site").replace(/^https?:\/\//, "").replace(/[^a-z0-9]/gi, "-");
      pdf.save(`onboarding-${safeName}.pdf`);
      toast.success("PDF downloaded");
    } catch (e: any) {
      toast.error(e.message || "PDF export failed");
    } finally {
      setExporting(false);
    }
  };

  // Load websites
  useEffect(() => {
    if (!user) return;
    supabase.from("websites").select("id, url, name").eq("user_id", user.id).then(({ data }) => {
      if (data) {
        setWebsites(data);
        if (data.length > 0 && !activeUrl) setActiveUrl(data[0].url);
      }
    });
  }, [user]);

  // Fake-ish progress while AI runs (target ~40s)
  useEffect(() => {
    if (!generating) { setProgress(0); return; }
    let p = 0;
    const id = setInterval(() => {
      p += 100 / 40;
      setProgress(Math.min(p, 95));
    }, 1000);
    return () => clearInterval(id);
  }, [generating]);

  const addWebsite = async () => {
    if (!user) return;
    const trimmed = newUrl.trim();
    if (!trimmed) return;
    if (!isProbablyValidUrl(trimmed)) {
      setUrlError(trimmed);
      return;
    }
    setAdding(true);
    try {
      const url = normalizeUrl(trimmed);
      const { data, error } = await supabase.from("websites").insert({ user_id: user.id, url, section: "docs" }).select("id, url, name").single();
      if (error) throw error;
      if (data) { setWebsites(prev => [...prev, data]); setActiveUrl(data.url); setNewUrl(""); setUrlError(null); }
    } catch (e: any) { toast.error(e.message); } finally { setAdding(false); }
  };

  const removeWebsite = async (id: string) => {
    await supabase.from("websites").delete().eq("id", id);
    setWebsites(prev => prev.filter(w => w.id !== id));
  };

  const askIntent = (mode: "docs" | "features") => {
    if (!activeUrl) { toast.error("Add a website first"); return; }
    setPendingMode(mode);
    setIntentOpen(true);
  };

  const generate = async (intent: FixIntent) => {
    if (!pendingMode) return;
    setGenerating(true);
    setDocs(null);
    setFeatures(null);
    setTab(pendingMode);
    try {
      const { data, error } = await supabase.functions.invoke("generate-tech-docs", {
        body: { url: activeUrl, mode: pendingMode, login_notes: intent.custom, audience_role: intent.role, depth: intent.level, technicality: intent.technicality },
      });
      if (error) throw error;
      if (data?.error) throw new Error(data.error);
      if (pendingMode === "docs") setDocs(data.data); else setFeatures(data.data);
      setProgress(100);
      toast.success(pendingMode === "docs" ? "Onboarding doc ready!" : "Feature scan complete!");
    } catch (e: any) { toast.error(e.message || "Generation failed"); } finally { setGenerating(false); setPendingMode(null); }
  };

  return (
    <div className="p-6 lg:p-10 max-w-[1400px] mx-auto w-full">
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mb-6">
        <div className="flex items-center gap-3 mb-1">
          <div className="w-8 h-8 rounded-lg bg-gradient-primary flex items-center justify-center">
            <BookOpen className="w-4 h-4 text-primary-foreground" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-foreground tracking-tight">Tech Docs</h1>
            <p className="text-sm text-muted-foreground">Plug in your URL — get a dev onboarding guide & feature map in ~40s.</p>
          </div>
        </div>
      </motion.div>

      <SuggestedWebsites section="docs" onAdopted={(w) => { setWebsites(p => [...p, w]); setActiveUrl(w.url); }} />

      {/* Website manager */}
      <div className="bg-card border border-border rounded-lg p-4 mb-4 shadow-card">
        <h3 className="text-sm font-semibold text-foreground mb-3">Pick a site to document</h3>
        <div className="flex gap-2 mb-3">
          <Input placeholder="https://yourwebsite.com" value={newUrl}
            onChange={(e) => { setNewUrl(e.target.value); setUrlError(null); }}
            onKeyDown={e => e.key === "Enter" && addWebsite()}
            className="bg-secondary border-border text-foreground" />
          <Button onClick={addWebsite} disabled={adding || !newUrl.trim()} size="sm" className="bg-gradient-primary text-primary-foreground">
            {adding ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus className="w-4 h-4" />}
          </Button>
        </div>

        {urlError && (
          <div className="mb-3">
            <SmartUrlError attemptedUrl={urlError} onPick={(u) => { setNewUrl(u); setUrlError(null); }} />
          </div>
        )}

        {websites.length > 0 && (
          <div className="space-y-1">
            {websites.map(w => (
              <button key={w.id}
                onClick={() => setActiveUrl(w.url)}
                className={`w-full flex items-center justify-between px-3 py-1.5 rounded text-sm transition-colors ${activeUrl === w.url ? "bg-primary/10 text-foreground" : "bg-secondary text-muted-foreground hover:text-foreground"}`}>
                <span className="font-mono text-xs truncate">{w.url}</span>
                <Trash2 className="w-3.5 h-3.5 opacity-50 hover:opacity-100 hover:text-destructive" onClick={(e) => { e.stopPropagation(); removeWebsite(w.id); }} />
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Generation actions */}
      <div className="flex items-center gap-2 mb-4">
        <Button onClick={() => askIntent("docs")} disabled={generating || !activeUrl} className="bg-gradient-primary text-primary-foreground">
          {generating && pendingMode === null && tab === "docs" ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <Wand2 className="w-4 h-4 mr-1.5" />}
          Generate onboarding doc
        </Button>
        <Button variant="outline" onClick={() => askIntent("features")} disabled={generating || !activeUrl} className="border-border text-foreground hover:bg-secondary">
          <ListPlus className="w-4 h-4 mr-1.5" />
          Generate feature map
        </Button>
        {docs && tab === "docs" && (
          <Button onClick={exportDocsPdf} disabled={exporting} variant="outline" className="border-border text-foreground hover:bg-secondary">
            {exporting ? <Loader2 className="w-4 h-4 animate-spin mr-1.5" /> : <Download className="w-4 h-4 mr-1.5" />}
            Export PDF
          </Button>
        )}
        {generating && (
          <div className="flex items-center gap-2 ml-2">
            <div className="w-32 h-1.5 bg-secondary rounded-full overflow-hidden">
              <motion.div className="h-full bg-gradient-primary" animate={{ width: `${progress}%` }} transition={{ ease: "linear" }} />
            </div>
            <span className="text-xs text-muted-foreground font-mono">{Math.round(progress)}%</span>
          </div>
        )}
      </div>

      {/* Output tabs */}
      <Tabs value={tab} onValueChange={(v) => setTab(v as any)}>
        <TabsList className="bg-secondary">
          <TabsTrigger value="docs" className="data-[state=active]:bg-card">Onboarding Doc</TabsTrigger>
          <TabsTrigger value="features" className="data-[state=active]:bg-card">Feature Map</TabsTrigger>
        </TabsList>

        <TabsContent value="docs" className="mt-4">
          {!docs && !generating && (
            <EmptyState icon={FileCode} title="No documentation yet" subtitle="Pick a website above and click Generate onboarding doc." />
          )}
          {docs && (
            <div className="space-y-4 bg-background p-2">
              <Section icon={Sparkles} title="Project Overview">
                <p className="text-sm text-foreground leading-relaxed">{docs.project_overview}</p>
              </Section>

              <Section icon={Layers} title="Likely Tech Stack">
                <div className="grid grid-cols-2 gap-2">
                  {docs.tech_stack_guess.map((t, i) => (
                    <div key={i} className="bg-secondary/40 border border-border rounded-md p-3">
                      <p className="text-sm font-semibold text-foreground">{t.name}</p>
                      <p className="text-xs text-muted-foreground mt-0.5">{t.why_we_think_so}</p>
                    </div>
                  ))}
                </div>
              </Section>

              <Section icon={Globe} title="Architecture">
                <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">{docs.architecture}</p>
              </Section>

              {docs.architecture_diagram && docs.architecture_diagram.length > 0 && (
                <Section icon={Workflow} title="Architecture Diagram">
                  <div className="grid grid-cols-2 gap-2">
                    {docs.architecture_diagram.map((c, i) => (
                      <div key={i} className="bg-secondary/40 border border-border rounded-md p-3">
                        <div className="flex items-center justify-between mb-1">
                          <p className="text-sm font-semibold text-foreground">{c.name}</p>
                          <Badge variant="outline" className="text-[9px] uppercase">{c.layer}</Badge>
                        </div>
                        <p className="text-xs text-muted-foreground">{c.role}</p>
                        {c.connects_to.length > 0 && (
                          <p className="text-[10px] text-muted-foreground/70 mt-1.5">↳ {c.connects_to.join(", ")}</p>
                        )}
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {docs.database_schema_guess && docs.database_schema_guess.length > 0 && (
                <Section icon={Database} title="Likely Database Schema">
                  <div className="space-y-2">
                    {docs.database_schema_guess.map((t, i) => (
                      <div key={i} className="bg-secondary/40 border border-border rounded-md p-3">
                        <p className="text-sm font-semibold text-foreground">{t.name}</p>
                        <p className="text-xs text-muted-foreground mb-1.5">{t.purpose}</p>
                        <div className="flex flex-wrap gap-1">
                          {t.key_fields.map((f, j) => (
                            <code key={j} className="text-[10px] bg-secondary px-1.5 py-0.5 rounded font-mono text-foreground">{f}</code>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {docs.user_workflows && docs.user_workflows.length > 0 && (
                <Section icon={Workflow} title="Common User Workflows">
                  <div className="space-y-3">
                    {docs.user_workflows.map((w, i) => (
                      <div key={i}>
                        <p className="text-sm font-semibold text-foreground mb-1">{w.name}</p>
                        <ol className="space-y-0.5 list-decimal list-inside">
                          {w.steps.map((s, j) => (
                            <li key={j} className="text-xs text-muted-foreground">{s}</li>
                          ))}
                        </ol>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              {docs.integrations && docs.integrations.length > 0 && (
                <Section icon={Plug} title="Integrations">
                  <div className="grid grid-cols-2 gap-2">
                    {docs.integrations.map((it, idx) => (
                      <div key={idx} className="bg-secondary/40 border border-border rounded-md p-2">
                        <p className="text-sm font-semibold text-foreground">{it.name}</p>
                        <p className="text-xs text-muted-foreground">{it.purpose}</p>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

              <Section icon={ChevronRight} title="Key Pages">
                <div className="space-y-1.5">
                  {docs.key_pages.map((p, i) => (
                    <div key={i} className="flex items-baseline gap-3 text-sm">
                      <span className="font-mono text-primary text-xs flex-shrink-0">{p.path}</span>
                      <span className="text-muted-foreground">{p.purpose}</span>
                    </div>
                  ))}
                </div>
              </Section>

              <Section icon={ListChecks} title="Local Setup">
                <ol className="space-y-1.5 list-decimal list-inside">
                  {docs.local_setup.map((s, i) => (
                    <li key={i} className="text-sm text-foreground">{s}</li>
                  ))}
                </ol>
              </Section>

              <Section icon={Lock} title="Likely Env Vars">
                <div className="flex flex-wrap gap-1.5">
                  {docs.env_vars_likely.map((v, i) => (
                    <code key={i} className="text-xs bg-secondary px-2 py-1 rounded font-mono text-foreground">{v}</code>
                  ))}
                </div>
              </Section>

              <Section icon={AlertTriangle} title="Gotchas">
                <ul className="space-y-1.5">
                  {docs.gotchas.map((g, i) => (
                    <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                      <AlertTriangle className="w-3.5 h-3.5 text-warning flex-shrink-0 mt-0.5" />
                      <span>{g}</span>
                    </li>
                  ))}
                </ul>
              </Section>

              <Section icon={ListChecks} title="First Week Checklist">
                <ul className="space-y-1.5">
                  {docs.first_week_checklist.map((c, i) => (
                    <li key={i} className="text-sm text-foreground flex items-start gap-2">
                      <input type="checkbox" className="mt-0.5 accent-primary" />
                      <span>{c}</span>
                    </li>
                  ))}
                </ul>
              </Section>
            </div>
          )}
        </TabsContent>

        <TabsContent value="features" className="mt-4">
          {!features && !generating && (
            <EmptyState icon={ListPlus} title="No feature map yet" subtitle="Pick a website above and click Generate feature map." />
          )}
          {features && (
            <div className="space-y-4">
              <Section icon={Sparkles} title="Summary">
                <p className="text-sm text-foreground leading-relaxed">{features.summary}</p>
              </Section>

              <Section icon={ListChecks} title={`Detected Features (${features.detected.length})`}>
                <div className="grid grid-cols-2 gap-2">
                  {features.detected.map((f, i) => (
                    <div key={i} className="bg-secondary/40 border border-border rounded-md p-3">
                      <div className="flex items-center justify-between mb-1">
                        <p className="text-sm font-semibold text-foreground">{f.name}</p>
                        <Badge variant="outline" className="text-[9px] uppercase">{f.confidence}</Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">{f.description}</p>
                      <Badge variant="secondary" className="text-[9px] mt-2 uppercase">{f.category}</Badge>
                    </div>
                  ))}
                </div>
              </Section>

              <Section icon={Sparkles} title="Recommended Additions">
                <div className="space-y-2">
                  {features.recommended.map((r, i) => (
                    <div key={i} className="bg-primary/5 border border-primary/20 rounded-md p-3">
                      <div className="flex items-center justify-between mb-1">
                        <p className="text-sm font-semibold text-foreground">{r.name}</p>
                        <Badge className={`text-[9px] uppercase ${r.impact === "high" ? "bg-destructive" : r.impact === "medium" ? "bg-warning" : "bg-secondary"}`}>{r.impact} impact</Badge>
                      </div>
                      <p className="text-xs text-muted-foreground">{r.why}</p>
                    </div>
                  ))}
                </div>
              </Section>
            </div>
          )}
        </TabsContent>
      </Tabs>

      <FixIntentDialog
        open={intentOpen}
        onOpenChange={setIntentOpen}
        onConfirm={generate}
        title={pendingMode === "features" ? "How deep should the feature scan go?" : "How detailed should the doc be?"}
        description="Quick = bullet summary. Standard = balanced. Deep = thorough analysis. Custom = tell us exactly what you want."
      />

      
    </div>
  );
};

const Section = ({ icon: Icon, title, children }: { icon: any; title: string; children: React.ReactNode }) => (
  <div className="bg-card border border-border rounded-lg p-4 shadow-card">
    <h3 className="text-sm font-semibold text-foreground flex items-center gap-2 mb-3">
      <Icon className="w-4 h-4 text-primary" /> {title}
    </h3>
    {children}
  </div>
);

const EmptyState = ({ icon: Icon, title, subtitle }: { icon: any; title: string; subtitle: string }) => (
  <div className="bg-card border border-border rounded-lg p-10 text-center shadow-card">
    <Icon className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
    <p className="text-sm font-medium text-foreground mb-1">{title}</p>
    <p className="text-xs text-muted-foreground">{subtitle}</p>
  </div>
);

export default TechDocs;
